#!/usr/bin/env bash

doas=$(eval "which doas" || eval "which sudo")

mkdir build
pushd build
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_WAYLAND_GRIM=ON ../
  make -j9
popd

$doas cp build/src/flameshot /usr/bin/
